name: Android CI

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  createArtifacts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Read Go version from project
      run: echo "GO_VERSION=$(grep -E "^de\.felixnuesse\.extract\.goVersion=" gradle.properties | cut -d'=' -f2)"
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Set up Go from gradle.properties
      uses: actions/setup-go@v4
      with:
        go-version: '${{env.GO_VERSION}}'
      id: go
    - name: Setup Android SDK/NDK
      uses: android-actions/setup-android@v3
    - name: Install NDK from gradle.properties
      run: |
        NDK_VERSION="$(grep -E "^de\.felixnuesse\.extract\.ndkVersion=" gradle.properties | cut -d'=' -f2)"
        sdkmanager "ndk;${NDK_VERSION}"
    - name: Build app
      run: ./gradlew assembleOssDebug
    - name: Upload APK (arm)
      uses: actions/upload-artifact@v4
      with:
        name: nightly-armeabi.apk
        path: ${{ github.workspace }}/app/build/outputs/apk/oss/debug/*-oss-armeabi-v7a-debug.apk
    - name: Upload APK (arm64)
      uses: actions/upload-artifact@v4
      with:
        name: nightly-arm64.apk
        path: ${{ github.workspace }}/app/build/outputs/apk/oss/debug/*-oss-arm64-v8a-debug.apk
    - name: Upload APK (x86)
      uses: actions/upload-artifact@v4
      with:
        name: nightly-x86.apk
        path: ${{ github.workspace }}/app/build/outputs/apk/oss/debug/*-oss-x86-debug.apk
    - name: Upload APK (arm)
      uses: actions/upload-artifact@v4
      with:
        name: nightly-x64.apk
        path: ${{ github.workspace }}/app/build/outputs/apk/oss/debug/*-oss-x86_64-debug.apk
    - name: Upload APK (universal)
      uses: actions/upload-artifact@v4
      with:
        name: nightly-universal.apk
        path: ${{ github.workspace }}/app/build/outputs/apk/oss/debug/*-oss-universal-debug.apk
        retention-days: 14